sudo: required
services:
  - docker
before_install:
  - docker build -t amolmathdevaru/npm-package1 -f Dockerfile.dev .

script:
  - docker run amolmathdevaru/npm-package npm run test -- --coverage    
